# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'JoinWithMe' do

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Database'

 # pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
pod 'XCDYouTubeKit', '~> 2.5'
